[package]
name = "clicker"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.29.0"
strum = "0.27.2"
strum_macros = "0.27.2"
log = "0.4.27"
log4rs = { version = "1.3.0", features = ["console_appender", "file_appender"] }
